### ISSUE TITLE
ADMIN

### ISSUE THREAD

**Issue by No3ml3** [WildCodeSchool/202302-orleans-php-project-inovin#209]
- la note des vins ne sert à rien ?
- On peut créer une séance avec une date passée, pas très logique ?
- on n'a pas moyen de voir les inscrits à une séance ?

**Comment by BENJAMIN-SAUSSAYE** [comment]
Melvin ok a fait la date et le nombre d'utilisateurs inscris.
Benjamin ok fait Note de vin remplacé par les likes.
